export const DATA = [
  {
    id: "0",
    scientificName: "Monstera Deliciosa",
    alias: "Beavertail Cactus",
    room: "Bedroom's windowsill",
    period: 2,
    portion: 50,
    image: "https://picsum.photos/seed/696/3000/2000",
  },
  {
    id: "1",
    scientificName: null,
    alias: "Vatikalive Canna",
    room: "Kitchen's windowsill",
    period: 1,
    portion: 100,
    image: "https://picsum.photos/seed/688/3000/2000",
  },
  {
    id: "2",
    scientificName: "Sansevieria Trifasciata",
    alias: "Snake Plant",
    room: "Living Room",
    period: 3,
    portion: 200,
    image: "https://picsum.photos/seed/680/3000/2000",
  },

  {
    id: "3",
    scientificName: "Monstera Deliciosa",
    alias: "Beavertail Cactus",
    room: "Bedroom's windowsill",
    period: 2,
    portion: 50,
    image: "https://picsum.photos/seed/695/3000/2000",
  },
  {
    id: "4",
    scientificName: null,
    alias: "Vatikalive Canna",
    room: "Kitchen's windowsill",
    period: 1,
    portion: 100,
    image: "https://picsum.photos/seed/690/3000/2000",
  },
  {
    id: "5",
    scientificName: "Sansevieria Trifasciata",
    alias: "Snake Plant",
    room: "Living Room",
    period: 3,
    portion: 200,
    image: "https://picsum.photos/seed/580/3000/2000",
  },
];
